language: python

os:
  - linux

python:
  - "3.5"
  - "3.6"

branches:
  only:
    - master
    - development

notifications:
  email:
  - abelcarreras83@gmail.com

install:
    - pip install coverage
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../pyqchem -m unittest discover . "rasci_t*.py"

after_success:
    - coveralls
    - cd ..
